version: "3.7"

services:

  frontend:

      build:

        context : .

        dockerfile : Dockerfile

      depends_on:

        - reversproxy

      expose :

        - "5000"

      restart : always

  reversproxy:

      image: nginx:alpine

      volumes:

        - "./nginx.conf:/etc/nginx/nginx.conf:ro"

      ports:

        - "4001:80"

      restart : always