pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'docker build -t dotnet .'
                bat "\"C:/Program Files/dotnet/dotnet.exe\" restore \"${workspace}/MVC Project.sln\""
                bat "\"C:/Program Files/dotnet/dotnet.exe\" build \"${workspace}/MVC Project.sln\""
                
            }
        }
        stage('Running unit tests') {
            steps {
                bat returnStatus: true, script: "\"C:/Program Files/dotnet/dotnet.exe\" dotnet test \"${workspace}/MVC Project.sln\" "
                }
        }
        stage('Publish HTML report') {
            steps {
                publishHTML(target: [allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: 'Code Coverage Report'])
  }
}
   
}
}