pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'mcr.microsoft.com/dotnet/aspnet:5.0' }
            }
            steps {
                bat 'docker build -t dotnet .'
                bat 'dotnet --version'
            }
        }

    }
}