pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'docker build -t dotnet .'
                bat "\"C:/Program Files/dotnet/dotnet.exe\" restore \"${workspace}/MVC Project.sln\""
                bat "\"C:/Program Files/dotnet/dotnet.exe\" build \"${workspace}/MVC Project.sln\""
                
            }
        }
        stage('Running unit tests') {
            steps {
                bat "dotnet add ${workspace}/C:/Users/PC DEV2/Desktop/MyProject/MVC Test Project/MVC Test Project.csproj package JUnitTestLogger --version 1.1.0"
                bat "dotnet test ${workspace}/C:/Users/PC DEV2/Desktop/MyProject/MVC Test Project/MVC Test Project.csproj --logger \"junit;LogFilePath=\"${WORKSPACE}\"/TestResults/1.0.0.\"${env.BUILD_NUMBER}\"/results.xml\" --configuration release --collect \"Code coverage\""
                }
        }
   
}
}